### ISSUE TITLE
Add relayerUrl overrides to wallet module

### ISSUE THREAD

**Issue by MaximusHaximus** [near/near-fastauth-wallet#3]
We need to add the ability to override the relayerUrl that is being used by the fastauth wallet module in order to facilitate demo of custom relayers for @Patrick1904

API wise, we need to provide him with methods on the wallet object that allow him to set `relayerUrl` to a new value on-the-fly, and to _reset_ `relayerUrl` back to the same value the module was originally initialized with.

```javascript
setRelayerUrl( { relayerUrl } );
resetRelayerUrl();
```

The intention is for Patrick to be able to grab an instance of the fastauth wallet using basically the [same approach as was done here](https://github.com/near/near-discovery/blob/36efce9fcbd8dd649e1706010f8df9e0da42a721/src/pages/signin.tsx#L38).

**Comment by esaminu** [comment]
Completed in #4
